### ISSUE TITLE
Is something leaking out that should do?

### ISSUE THREAD

**Issue by piropiro2018** [owen9825/captcha-middleware#1]
python setup.py test   and
python setup.py install   success.

I added the code according to the example.
It did not solve.

at middleware.py　process_response(self, request, response, spider)
I added a debug log at the beginning and tried to execute it, but no log was output.
Is something leaking out that should do?

> 2019-05-16 14:07:37 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.logstats.LogStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.throttle.AutoThrottle']
2019-05-16 14:07:38 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.robotstxt.RobotsTxtMiddleware',
 'scrapy_proxies.RandomProxy',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'itemresearch.randomAgentMiddleware.MyUserAgentMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'captchaMiddleware.middleware.CaptchaMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy_splash.SplashCookiesMiddleware',
 'scrapy_splash.SplashMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2019-05-16 14:07:38 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy_splash.SplashDeduplicateArgsMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2019-05-16 14:07:38 [scrapy.middleware] INFO: Enabled item pipelines:
[]

User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
2019-05-16 14:07:51 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.amazon.co.jp/s/ref=lp_2131568051_nr_n_10?fst=as%3Aoff&rh=n%3A352484011%2Cn%3A%21361245011%2Cn%3A2131568051%2Cn%3A2131579051&bbn=2131568051&ie=UTF8&qid=1557726778&rnid=2131568051> (referer: None)
2019-05-16 14:08:01 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.amazon.co.jp/s/ref=lp_2131590051_nr_n_12?fst=as%3Aoff&rh=n%3A2229202051%2Cn%3A%212229203051%2Cn%3A2230804051%2Cn%3A2230781051%2Cn%3A2131590051%2Cn%3A2131604051&bbn=2131590051&ie=UTF8&qid=1557726660&rnid=2131590051> (referer: None)
2019-05-16 14:08:07 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.amazon.co.jp/s/ref=lp_2131614051_nr_n_2?fst=as%3Aoff&rh=n%3A352484011%2Cn%3A%21361245011%2Cn%3A2131590051%2Cn%3A2131614051%2Cn%3A2131617051&bbn=2131614051&ie=UTF8&qid=1557726731&rnid=2131614051> (referer: None)
2019-05-16 14:08:07 [scrapy.core.engine] INFO: Closing spider (finished)

**setup.py**

`# -*- coding: utf-8 -*-

# Scrapy settings for itemresearch project
#
# For simplicity, this file contains only settings considered important or
# commonly used. You can find more settings consulting the documentation:
#
#     https://doc.scrapy.org/en/latest/topics/settings.html
#     https://doc.scrapy.org/en/latest/topics/downloader-middleware.html
#     https://doc.scrapy.org/en/latest/topics/spider-middleware.html

BOT_NAME = 'itemresearch'

SPIDER_MODULES = ['itemresearch.spiders']
NEWSPIDER_MODULE = 'itemresearch.spiders'

# Crawl responsibly by identifying yourself (and your website) on the user-agent
#USER_AGENT = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36'
USER_AGENTS_LIST = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763",
    "Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; MDDCJS; rv:11.0) like Gecko",
]

# Obey robots.txt rules
ROBOTSTXT_OBEY = True

# Configure maximum concurrent requests performed by Scrapy (default: 16)
#CONCURRENT_REQUESTS = 32

# Configure a delay for requests for the same website (default: 0)
# See https://doc.scrapy.org/en/latest/topics/settings.html#download-delay
# See also autothrottle settings and docs
DOWNLOAD_DELAY = 3
# The download delay setting will honor only one of:
#CONCURRENT_REQUESTS_PER_DOMAIN = 16
#CONCURRENT_REQUESTS_PER_IP = 16

# Disable cookies (enabled by default)
#COOKIES_ENABLED = False

# Disable Telnet Console (enabled by default)
#TELNETCONSOLE_ENABLED = False

# Override the default request headers:
#DEFAULT_REQUEST_HEADERS = {
#   'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
#   'Accept-Language': 'en',
#}

# Enable or disable spider middlewares
# See https://doc.scrapy.org/en/latest/topics/spider-middleware.html
SPIDER_MIDDLEWARES = {
    'scrapy_splash.SplashDeduplicateArgsMiddleware': 100,
}

# Retry many times since proxies often fail
RETRY_TIMES = 10
# Retry on most error codes since proxies fail for different reasons
RETRY_HTTP_CODES = [500, 503, 504, 400, 403, 404, 408]

# Enable or disable downloader middlewares
# See https://doc.scrapy.org/en/latest/topics/downloader-middleware.html
DOWNLOADER_MIDDLEWARES = {
    'scrapy_splash.SplashCookiesMiddleware': 723,
    'scrapy_splash.SplashMiddleware': 725,
    'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware': 810,
    'scrapy.downloadermiddlewares.retry.RetryMiddleware': 90,
    'scrapy_proxies.RandomProxy': 100,
    'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware': 110,
    'captchaMiddleware.middleware.CaptchaMiddleware':500,
    'scrapy.downloadermiddleware.useragent.UserAgentMiddleware': None,
    'itemresearch.randomAgentMiddleware.MyUserAgentMiddleware': 400,
}

# Proxy list containing entries like
# http://host1:port
# http://username:password@host2:port
# http://host3:port
# ...
PROXY_LIST = '/home/itsumohima0112/itemresearch/itemresearch/proxy.txt'

# Proxy mode
# 0 = Every requests have different proxy
# 1 = Take only one proxy from the list and assign it to every requests
# 2 = Put a custom proxy to use in the settings
PROXY_MODE = 0

# If proxy mode is 2 uncomment this sentence :
#CUSTOM_PROXY = "http://86.34.150.170:8181"

# Enable or disable extensions
# See https://doc.scrapy.org/en/latest/topics/extensions.html
#EXTENSIONS = {
#    'scrapy.extensions.telnet.TelnetConsole': None,
#}

# Configure item pipelines
# See https://doc.scrapy.org/en/latest/topics/item-pipeline.html
#ITEM_PIPELINES = {
#    'itemresearch.pipelines.ItemresearchPipeline': 300,
#}

# Enable and configure the AutoThrottle extension (disabled by default)
# See https://doc.scrapy.org/en/latest/topics/autothrottle.html
AUTOTHROTTLE_ENABLED = True
# The initial download delay
AUTOTHROTTLE_START_DELAY = 15
# The maximum download delay to be set in case of high latencies
AUTOTHROTTLE_MAX_DELAY = 60
# The average number of requests Scrapy should be sending in parallel to
# each remote server
#AUTOTHROTTLE_TARGET_CONCURRENCY = 1.0
# Enable showing throttling stats for every response received:
AUTOTHROTTLE_DEBUG = False

# Enable and configure HTTP caching (disabled by default)
# See https://doc.scrapy.org/en/latest/topics/downloader-middleware.html#httpcache-middleware-settings
#HTTPCACHE_ENABLED = True
#HTTPCACHE_EXPIRATION_SECS = 0
#HTTPCACHE_DIR = 'httpcache'
#HTTPCACHE_IGNORE_HTTP_CODES = []
#HTTPCACHE_STORAGE = 'scrapy.extensions.httpcache.FilesystemCacheStorage'

DEPTH_LIMIT = 35
START_URLS = "/home/itsumohima0112/itemresearch/itemresearch/target/site.txt"
SPLASH_URL = 'http://XXXXXXXXXXXXX/'
DUPEFILTER_CLASS = 'scrapy_splash.SplashAwareDupeFilter'
HTTPCACHE_STORAGE = 'scrapy_splash.SplashAwareFSCacheStorage'
`

**spider.py**

`# -*- coding: utf-8 -*-
import scrapy
from scrapy.linkextractors import LinkExtractor
from scrapy.spiders import CrawlSpider, Rule
from scrapy.conf import settings
from pytz import timezone
from datetime import datetime as dt
from itemresearch.items import MyproductsItem
from scrapy_splash import SplashRequest
from captchaMiddleware.middleware import RETRY_KEY

class SearchproductsSpider(CrawlSpider):
    start_urls = []

    name = 'searchProducts'
    allowed_domains = ['www.amazon.co.jp']
    def __init__(self, *args, **kwargs):
        super(SearchproductsSpider, self).__init__(*args, **kwargs)

        f = open(settings.get("START_URLS"))
        urls = f.readlines()
        f.close()

        urls2 = []
        for url in urls :
               if url.strip(' ')[:1] != "/" :
                   urls2.append(url)

        self.start_urls = [url.replace('\r','').replace('\n','') for url in urls2 if url != "\n"]

        self.deny_list = []
        self.rules = (
             Rule(LinkExtractor(deny=self.deny_list,unique=True), callback='parse'),
             Rule(LinkExtractor(restrict_xpaths='//a[@id="pagnNextLink"]/@href'), follow=True)
            )
        self._compile_rules()

    def start_requests(self):
        for url in self.start_urls:
            yield scrapy.Request(url=url, callback=self.parse,
                meta={RETRY_KEY:0})
        
    def parse(self, response):
        #if not hxs.select('//get/site/logo'):
        #    yield Request(url=response.url, dont_filter=True)
        for sel in response.xpath('//div[@class="s-item-container"]'):

            #title
            title_str = sel.xpath('div[@class="a-row a-spacing-none"]/div[@class="a-row a-spacing-mini"]/a[@class="a-link-normal s-access-detail-page s-color-twister-title-link a-text-normal"]/@title').get()

            now = dt.now(timezone('Asia/Tokyo'))
            date = now.strftime('%Y-%m-%d')
            jst_time = now.strftime('%Y-%m-%dT%H-%M-%S')

            product = MyproductsItem()

            product['title'] = title_str

            yield product

`

**Comment by owen9825** [comment]
I'm not quite sure what you mean about the output − your spider should produce a text file in your project directory. The CAPTCHA solver only says anything in the debug logs and I'm not sure if you're running your spider with debug-level logging.

Anyway, in reinstalling this, I realised that I need to update the setup script a bit btw. I'll be able to update it this weekend, along with potentially something relevant to your situation.

**Comment by piropiro2018** [comment]
In my execute log,
[scrapy.core.engine] DEBUG: Crawled (200) -output,
there are CAPTCHA page contain.

I wanted to know if it was running the captchaMiddleware.middleware.CaptchaMiddleware.

There are many other middlewares that output DEBUG log, so I thought that I could confirm it.

**Comment by owen9825** [comment]
Yeah you'll see in `middleware.py` that if a CAPTCHA puzzle is noticed, there'll be a log that either we're giving up or a solution is being proposed.

**Comment by piropiro2018** [comment]
Thank you, owen9825 .
Now that the restriction has been lifted, it is difficult for the image to appear. I will confirm the next opportunity.
